clear all;
clc;
close all;
y_pred = DMget_getDemandModel([pwd,'\','DST_20180731KEPRI2.csv'],...
                        [pwd,'\','DFP_20180731KEPRI2.csv'],...
                        [pwd,'\','ResultData.csv'])